import json
import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()

# ─── Helpers ──────────────────────────────────────────────────────────────────

def _tier(score: int) -> str:
    if score >= 9:
        return "hot"
    if score >= 7:
        return "solid"
    return "maybe"

def _emoji(score: int) -> str:
    if score >= 9:
        return "🔥"
    if score >= 7:
        return "⭐"
    return "👀"

def _color(score: int) -> str:
    if score >= 9:
        return "#FF6B35"
    if score >= 7:
        return "#4ECDC4"
    return "#95A5A6"

def _bucket(jobs: list[dict], tier: str) -> list[dict]:
    return [j for j in jobs if _tier(j["score"]) == tier]


# ─── HTML builder ─────────────────────────────────────────────────────────────

def _build_html(jobs: list[dict], today: str) -> str:
    hot    = _bucket(jobs, "hot")
    solid  = _bucket(jobs, "solid")
    maybe  = _bucket(jobs, "maybe")

    def section(title: str, color: str, items: list[dict]) -> str:
        if not items:
            return ""
        cards = ""
        wm_badge = {"remote": "🌍", "hybrid": "🏢", "on-site": "🏙️", "unknown": "❓"}
        size_badge_map = {"startup":"🚀","scaleup":"⚡","sme":"🏢","large":"🏦","unknown":""}
        contract_badge_map = {"permanent":"💼","freelance":"🔄","contract":"📋","internship":"🎓","unknown":""}
        for j in items:
            posted = j.get("posted_date") or ""
            wm = j.get("work_mode") or "unknown"
            badge = wm_badge.get(wm, "❓")
            sz = size_badge_map.get(j.get("company_size") or "unknown", "")
            ct = contract_badge_map.get(j.get("contract_type") or "unknown", "")
            extra = " ".join(b for b in [sz, ct] if b)
            summary = j.get("summary") or ""
            summary_html = f'<p style="color:#bbb;font-size:12px;margin:4px 0">{summary}</p>' if summary else ""
            cards += f"""
            <div style="border-left:3px solid {color};padding:8px 12px;margin:10px 0;background:#1a1a1a;border-radius:0 4px 4px 0">
              <b style="color:{color}">{_emoji(j['score'])} {j['title']} @ {j['company']}</b><br>
              <span style="color:#aaa;font-size:12px">{j.get('location','Remote')} {badge} {extra} · {j.get('source','')} · {posted}</span><br>
              <i style="color:#ccc;font-size:13px">{j.get('reason','')}</i>
              {summary_html}
              <a href="{j.get('url','#')}" style="color:{color};font-size:13px">→ Apply</a>
            </div>"""
        return f"""
        <h2 style="color:{color};border-bottom:1px solid {color};padding-bottom:4px">{title}</h2>
        {cards}"""

    body = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="background:#111;color:#eee;font-family:sans-serif;max-width:700px;margin:auto;padding:24px">
  <h1 style="color:#fff">🎯 Job Digest — {today}</h1>
  <p style="color:#888">{len(jobs)} offres analysées · {len(hot)}🔥 · {len(solid)}⭐ · {len(maybe)}👀</p>
  {section("🔥 Apply Now (9-10)", "#FF6B35", hot)}
  {section("⭐ Worth Checking (7-8)", "#4ECDC4", solid)}
  {section("👀 Maybe (5-6)", "#95A5A6", maybe)}
  <p style="color:#555;font-size:11px;margin-top:32px">Generated by job_agent</p>
</body>
</html>"""
    return body


# ─── send_email_digest ────────────────────────────────────────────────────────

def send_email_digest(jobs: list[dict]) -> None:
    today = date.today().strftime("%Y-%m-%d")
    hot   = len(_bucket(jobs, "hot"))
    solid = len(_bucket(jobs, "solid"))
    maybe = len(_bucket(jobs, "maybe"))
    subject = f"🎯 Job Digest [{today}] — {hot}🔥 {solid}⭐ {maybe}👀"
    html = _build_html(jobs, today)

    gmail_from = os.getenv("GMAIL_FROM")
    app_password = os.getenv("GMAIL_APP_PASSWORD")
    notify_to = os.getenv("NOTIFY_TO")

    if not all([gmail_from, app_password, notify_to]):
        output_dir = os.path.join(os.path.dirname(__file__), "outputs")
        os.makedirs(output_dir, exist_ok=True)
        preview_path = os.path.join(output_dir, f"email_preview_{today}.html")
        with open(preview_path, "w", encoding="utf-8") as f:
            f.write(html)
        print(f"EMAIL_PREVIEW: open {preview_path}")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_from
    msg["To"] = notify_to
    msg.attach(MIMEText(html, "html", "utf-8"))

    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.login(gmail_from, app_password)
        smtp.sendmail(gmail_from, notify_to, msg.as_string())

    print(f"✅ Email sent to {notify_to} — {subject}")


# ─── export_joplin ────────────────────────────────────────────────────────────

JOPLIN_API = "http://localhost:41184"
JOPLIN_NOTEBOOK_ID = "7c08b4b26c7c4a4682f6a25651cd8f9d"  # Job Digest (under 00 pro)


def export_joplin(jobs: list[dict]) -> None:
    import urllib.request
    import urllib.error

    today = date.today()
    today_str = today.strftime("%Y-%m-%d")
    today_human = today.strftime("%d %B %Y")

    hot   = _bucket(jobs, "hot")
    solid = _bucket(jobs, "solid")
    maybe = _bucket(jobs, "maybe")

    WORK_MODE_BADGE = {
        "remote":   "🌍 Remote",
        "hybrid":   "🏢 Hybrid",
        "on-site":  "🏙️ On-site",
        "unknown":  "❓ Mode inconnu",
    }
    COMPANY_SIZE_BADGE = {
        "startup":  "🚀 Startup",
        "scaleup":  "⚡ Scale-up",
        "sme":      "🏢 SME",
        "large":    "🏦 Large",
        "unknown":  "",
    }
    CONTRACT_BADGE = {
        "permanent":  "💼 Permanent",
        "freelance":  "🔄 Freelance",
        "contract":   "📋 Contract",
        "internship": "🎓 Internship",
        "unknown":    "",
    }

    def _fmt_location(loc: str) -> str:
        loc_l = (loc or "").lower()
        if "hybrid" in loc_l:
            return loc
        return "Remote"

    def md_section(title: str, items: list[dict]) -> str:
        if not items:
            return ""
        lines = [f"## {title}\n"]
        for j in items:
            posted = j.get("posted_date") or today_str
            location = _fmt_location(j.get("location", ""))
            work_mode = j.get("work_mode") or "unknown"
            badge = WORK_MODE_BADGE.get(work_mode, "❓ Mode inconnu")
            summary = j.get("summary") or ""
            company_size = j.get("company_size") or "unknown"
            contract_type = j.get("contract_type") or "unknown"
            size_badge = COMPANY_SIZE_BADGE.get(company_size, "")
            contract_badge = CONTRACT_BADGE.get(contract_type, "")
            meta_badges = " · ".join(b for b in [badge, size_badge, contract_badge] if b)
            lines.append(f"### {j['title']} @ {j['company']}")
            lines.append(f"**Score {j['score']}/10** · {j.get('source','')} · {meta_badges} · 🗓 {posted}")
            lines.append(f"> *{j.get('reason','')}*")
            if summary:
                lines.append(f"\n{summary}")
            lines.append(f"\n🔗 [Postuler]({j.get('url','#')})")
            lines.append("\n---")
        return "\n".join(lines) + "\n"

    content = f"""# 🎯 Job Digest — {today_human}
> {len(jobs)} offres · {len(hot)}🔥 · {len(solid)}⭐ · {len(maybe)}👀

{md_section("🔥 Apply Now", hot)}
{md_section("⭐ Worth Checking", solid)}
{md_section("👀 Maybe", maybe)}"""

    # Always save local .md
    output_dir = os.path.join(os.path.dirname(__file__), "outputs")
    os.makedirs(output_dir, exist_ok=True)
    local_path = os.path.join(output_dir, f"jobs_{today_str}.md")
    with open(local_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"📝 Markdown saved → {local_path}")

    # Push to Joplin via API
    token = os.getenv("JOPLIN_TOKEN")
    if not token:
        print("⚠️  JOPLIN_TOKEN not set — skipping Joplin API push")
        return

    payload = json.dumps({
        "title": f"🎯 Job Digest — {today_human}",
        "body": content,
        "parent_id": JOPLIN_NOTEBOOK_ID,
    }).encode("utf-8")

    try:
        req = urllib.request.Request(
            f"{JOPLIN_API}/notes?token={token}",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        resp = json.loads(urllib.request.urlopen(req).read())
        print(f"✅ Joplin note created → '{resp['title']}' (id: {resp['id']})")
    except urllib.error.URLError as e:
        print(f"⚠️  Joplin API unreachable: {e} — note saved locally only")
